<html>
    <head>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    </head>
    <body>
        <button id="show-login" class="btn btn-primary" data-toggle="modal" data-target="#myModal" style="display: none">
            Log in
        </button>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">Log in</h4>
                    </div> <!-- /.modal-header -->
                    <div class="modal-body">
                        <form id="login-form" role="form" method="POST" action="Session/doLogin">
                            <div class="form-group">
                                <div class="input-group">
                                    <input name="username" type="text" class="form-control" id="uLogin" placeholder="Login">
                                    <label for="uLogin" class="input-group-addon glyphicon glyphicon-user"  style="top:0"></label>
                                </div>
                            </div> <!-- /.form-group -->
                            <div class="form-group">
                                <div class="input-group">
                                    <input name="password" type="password" class="form-control" id="uPassword" placeholder="Password">
                                    <label for="uPassword" class="input-group-addon glyphicon glyphicon-lock"  style="top:0"></label>
                                </div> <!-- /.input-group -->
                            </div> <!-- /.form-group -->
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Remember me
                                </label>
                            </div> <!-- /.checkbox -->
                        </form>
                    </div> <!-- /.modal-body -->
                    <div class="modal-footer">
                        <button id="form-submit" class="form-control btn btn-primary">Ok</button>
                        <div class="progress">
                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="100" style="width: 0%;">
                                <span class="sr-only">progress</span>
                            </div>
                        </div>
                    </div> <!-- /.modal-footer -->
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <footer>
            <script src="//code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
            <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
            <script>
                jQuery(document).ready(function () {
                    jQuery('#show-login').trigger('click');
                    jQuery('#form-submit').click(function () {
                        jQuery('#login-form').submit();
                    });
                });
            </script>
        </footer>
    </body>
</html>